CREATE TABLE donations(

id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
donor_name VARCHAR(200) NOT NULL,
donor_email VARCHAR(200) NOT NULL,
donor_phone VARCHAR(30) NOT NULL,
type VARCHAR(30),
amount NUMERIC (12,2),
description TEXT,
status VARCHAR(30),
donation_date DATE,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP

);