CREATE TABLE staff(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    phone_number VARCHAR(30) NOT NULL,
    staff_role VARCHAR(30),
    hire_date DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP

);
